name: mjk_lint_rules
version: 4.0.3
description: Lint rules for Dart and Flutter projects.
repository: "https://github.com/MbIXjkee/mjk-lint-rules"
issue_tracker: "https://github.com/MbIXjkee/mjk-lint-rules/issues"

topics:
  - analysis
  - lints

# No need any dependencies
# dependencies:

environment:
  sdk: ">=3.8.0 <4.0.0"